# -*- coding: utf-8 -*-
"""Salmon_Fish_Disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BXclTnZaSLQkaK10aD1Wv60oPXU67ri

**Salmon Fish Disease Classification**


This work uses the following public **dataset**:

Ahmed, Md Shoaib (2024), “SalmonScan: A Novel Image Dataset for Machine Learning and Deep Learning Analysis in Fish Disease Detection in Aquaculture”, Mendeley Data, V3.
DOI: 10.17632/x3fz2nfm4w.3
Dataset URL: https://data.mendeley.com/datasets/x3fz2nfm4w/3


The SalmonScan dataset contains salmon fish images categorized into two classes:

*   Fresh Salmon
*   Infected Salmon

The dataset is suitable for machine learning and deep learning-based fish disease detection in aquaculture systems.



Prepared by

Partha Pratim Ray, Sikkim University, India, May 24, 2026, parthapratimray1986@gmail.com, ppray@cus.ac.in
"""

#Cell 1: Install libraries
!pip -q install timm ultralytics transformers accelerate torchmetrics scikit-learn seaborn opencv-python pillow pandas openpyxl statsmodels

# Cell 2: Imports and seed
import os, zipfile, shutil, time, random
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from statsmodels.stats.contingency_tables import mcnemar

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models

import timm
from transformers import AutoModelForImageClassification

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", DEVICE)

# Cell 3: Download SalmonScan Version 3 and extract

DATA_DIR = Path("/content/salmonscan")
ZIP_PATH = Path("/content/salmonscan_v3.zip")

!rm -rf /content/salmonscan /content/salmonscan_v3.zip

!wget -O /content/salmonscan_v3.zip "https://data.mendeley.com/public-api/zip/x3fz2nfm4w/download/3"

print("Zip exists:", ZIP_PATH.exists())
print("Zip size MB:", ZIP_PATH.stat().st_size / (1024 * 1024))

DATA_DIR.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    print("First 50 zip entries:")
    for name in z.namelist()[:50]:
        print(name)
    z.extractall(DATA_DIR)

print("Extraction completed.")

# Cell 4: Extract nested SalmonScan.zip and discover images

INNER_ZIP = list(DATA_DIR.rglob("SalmonScan.zip"))

print("Nested zip files found:", INNER_ZIP)

if len(INNER_ZIP) == 0:
    raise ValueError("No nested SalmonScan.zip found.")

INNER_EXTRACT_DIR = DATA_DIR / "SalmonScan_extracted"
INNER_EXTRACT_DIR.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(INNER_ZIP[0], "r") as z:
    print("First 50 entries inside nested zip:")
    for name in z.namelist()[:50]:
        print(name)
    z.extractall(INNER_EXTRACT_DIR)

image_exts = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"}

image_paths = [
    p for p in INNER_EXTRACT_DIR.rglob("*")
    if p.is_file() and p.suffix.lower() in image_exts
]

print("Total image files found:", len(image_paths))

if len(image_paths) == 0:
    print("Folder tree sample:")
    for p in list(INNER_EXTRACT_DIR.rglob("*"))[:150]:
        print(p)
    raise ValueError("No images found inside nested zip.")

df = pd.DataFrame({"path": [str(p) for p in image_paths]})

def infer_label(path):
    s = str(path).lower()

    if "infected" in s or "infect" in s or "disease" in s:
        return "InfectedFish"
    elif "fresh" in s or "healthy" in s:
        return "FreshFish"
    else:
        return "Unknown"

df["label"] = df["path"].apply(infer_label)

print("\nDetected labels:")
print(df["label"].value_counts())

print("\nSample rows:")
print(df.head(10).to_string(index=False))

# Cell 5: Train/validation/test split

WORK_DIR = Path("/content/salmon_ready")

if WORK_DIR.exists():
    shutil.rmtree(WORK_DIR)

for split in ["train", "val", "test"]:
    for cls in ["FreshFish", "InfectedFish"]:
        (WORK_DIR / split / cls).mkdir(parents=True, exist_ok=True)

train_df, temp_df = train_test_split(
    df, test_size=0.30, stratify=df["label"], random_state=SEED
)

val_df, test_df = train_test_split(
    temp_df, test_size=0.50, stratify=temp_df["label"], random_state=SEED
)

for split_name, split_df in [("train", train_df), ("val", val_df), ("test", test_df)]:
    for _, row in split_df.iterrows():
        src = Path(row["path"])
        dst = WORK_DIR / split_name / row["label"] / src.name
        shutil.copy2(src, dst)

dist = []
for split in ["train", "val", "test"]:
    for cls in ["FreshFish", "InfectedFish"]:
        dist.append({
            "Split": split,
            "Class": cls,
            "Count": len(list((WORK_DIR / split / cls).glob("*")))
        })

dist_df = pd.DataFrame(dist)
print(dist_df.to_string(index=False))

# Cell 6: Plot class distribution

plt.figure(figsize=(7,4))
sns.barplot(data=dist_df, x="Split", y="Count", hue="Class")
plt.title("SalmonScan Train/Validation/Test Distribution")
plt.tight_layout()
plt.show()

# Cell 7: Data loaders

IMG_SIZE = 224
BATCH_SIZE = 32

train_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.15, contrast=0.15, saturation=0.10),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225])
])

eval_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406], [0.229,0.224,0.225])
])

train_ds = datasets.ImageFolder(WORK_DIR / "train", transform=train_tfms)
val_ds   = datasets.ImageFolder(WORK_DIR / "val", transform=eval_tfms)
test_ds  = datasets.ImageFolder(WORK_DIR / "test", transform=eval_tfms)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

class_names = train_ds.classes
num_classes = len(class_names)

print(class_names)

# Cell 8: Model factory with basic CNN + recent models

def build_model(model_name, num_classes=2):

    # Basic CNN / classical transfer-learning baselines
    if model_name == "alexnet":
        model = models.alexnet(weights=models.AlexNet_Weights.IMAGENET1K_V1)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)

    elif model_name == "vgg16":
        model = models.vgg16(weights=models.VGG16_Weights.IMAGENET1K_V1)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)

    elif model_name == "vgg19":
        model = models.vgg19(weights=models.VGG19_Weights.IMAGENET1K_V1)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)

    elif model_name == "resnet18":
        model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)
        model.fc = nn.Linear(model.fc.in_features, num_classes)

    elif model_name == "resnet50":
        model = models.resnet50(weights=models.ResNet50_Weights.IMAGENET1K_V2)
        model.fc = nn.Linear(model.fc.in_features, num_classes)

    elif model_name == "densenet121":
        model = models.densenet121(weights=models.DenseNet121_Weights.IMAGENET1K_V1)
        model.classifier = nn.Linear(model.classifier.in_features, num_classes)

    elif model_name == "inception_v3":
        model = models.inception_v3(weights=models.Inception_V3_Weights.IMAGENET1K_V1, aux_logits=True)
        model.fc = nn.Linear(model.fc.in_features, num_classes)

    elif model_name == "efficientnet_b0":
        model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)

    # Recent lightweight timm model from Hugging Face
    elif model_name == "hf_mobilenetv3_small_lamb":
        model = timm.create_model(
            "hf_hub:timm/mobilenetv3_small_100.lamb_in1k",
            pretrained=True,
            num_classes=num_classes
        )

    # Vision transformer baselines
    elif model_name == "vit_base":
        model = timm.create_model(
            "vit_base_patch16_224",
            pretrained=True,
            num_classes=num_classes
        )

    elif model_name == "swinv2_tiny":
        model = timm.create_model(
            "swinv2_tiny_window8_256",
            pretrained=True,
            num_classes=num_classes
        )

    # Domain-unrelated but requested HF ViT model; useful only as transfer baseline
    elif model_name == "falconsai_nsfw_vit":
        model = AutoModelForImageClassification.from_pretrained(
            "Falconsai/nsfw_image_detection",
            num_labels=num_classes,
            ignore_mismatched_sizes=True
        )

    else:
        raise ValueError(f"Unknown model: {model_name}")

    return model.to(DEVICE)

# Cell 9: Training loop

def forward_logits(model, x):
    out = model(x)
    if hasattr(out, "logits"):
        return out.logits
    if isinstance(out, tuple):
        return out[0]
    return out


def run_one_epoch(model, loader, optimizer=None):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    criterion = nn.CrossEntropyLoss()
    total_loss = 0
    all_y, all_pred, all_prob = [], [], []

    with torch.set_grad_enabled(is_train):
        for x, y in loader:
            x, y = x.to(DEVICE), y.to(DEVICE)

            logits = forward_logits(model, x)
            loss = criterion(logits, y)

            if is_train:
                optimizer.zero_grad()
                loss.backward()
                optimizer.step()

            probs = torch.softmax(logits, dim=1)[:, 1]
            preds = torch.argmax(logits, dim=1)

            total_loss += loss.item() * x.size(0)
            all_y.extend(y.cpu().numpy())
            all_pred.extend(preds.cpu().numpy())
            all_prob.extend(probs.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    acc = accuracy_score(all_y, all_pred)
    f1 = f1_score(all_y, all_pred)

    return avg_loss, acc, f1, np.array(all_y), np.array(all_pred), np.array(all_prob)


def train_model(model_name, epochs=10, lr=1e-4):
    model = build_model(model_name, num_classes)

    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=lr,
        weight_decay=1e-4
    )

    history = []
    best_f1 = -1
    best_path = f"/content/best_{model_name}.pt"

    for epoch in range(1, epochs + 1):
        tr_loss, tr_acc, tr_f1, *_ = run_one_epoch(model, train_loader, optimizer)
        va_loss, va_acc, va_f1, *_ = run_one_epoch(model, val_loader)

        row = {
            "epoch": epoch,
            "train_loss": tr_loss,
            "val_loss": va_loss,
            "train_acc": tr_acc,
            "val_acc": va_acc,
            "train_f1": tr_f1,
            "val_f1": va_f1
        }

        history.append(row)
        print(row)

        if va_f1 > best_f1:
            best_f1 = va_f1
            torch.save(model.state_dict(), best_path)

    model.load_state_dict(torch.load(best_path, map_location=DEVICE))
    return model, pd.DataFrame(history), best_path

# Cell 10: Select models to run

MODELS_TO_RUN = [
    # Basic CNN baselines
    "alexnet",
    "vgg16",
    "vgg19",
    "resnet18",
    "resnet50",
    "densenet121",
    "efficientnet_b0",

    # Recent/lightweight/requested models
    "hf_mobilenetv3_small_lamb",

    # Transformer models
    "vit_base",

    # Requested HF transfer baseline
    "falconsai_nsfw_vit"
]

all_histories = {}
trained_models = {}

for m in MODELS_TO_RUN:
    print("\n" + "="*80)
    print("Training:", m)
    print("="*80)

    try:
        model, hist, path = train_model(m, epochs=20, lr=1e-4)
        all_histories[m] = hist
        trained_models[m] = model
    except Exception as e:
        print(f"Skipped {m} due to error: {e}")

# Cell 11: Plot loss and accuracy

for model_name, hist in all_histories.items():

    plt.figure(figsize=(7,4))
    plt.plot(hist["epoch"], hist["train_loss"], marker="o", label="Train Loss")
    plt.plot(hist["epoch"], hist["val_loss"], marker="o", label="Validation Loss")
    plt.title(f"{model_name}: Loss Curve")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(7,4))
    plt.plot(hist["epoch"], hist["train_acc"], marker="o", label="Train Accuracy")
    plt.plot(hist["epoch"], hist["val_acc"], marker="o", label="Validation Accuracy")
    plt.title(f"{model_name}: Accuracy Curve")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Cell 12: Test metrics

def compute_metrics(y_true, y_pred, y_prob):
    cm = confusion_matrix(y_true, y_pred)
    tn, fp, fn, tp = cm.ravel()

    sensitivity = tp / (tp + fn + 1e-9)
    specificity = tn / (tn + fp + 1e-9)

    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall/Sensitivity": sensitivity,
        "Specificity": specificity,
        "F1-score": f1_score(y_true, y_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_true, y_pred),
        "MCC": matthews_corrcoef(y_true, y_pred),
        "Cohen Kappa": cohen_kappa_score(y_true, y_pred),
        "ROC-AUC": roc_auc_score(y_true, y_prob),
        "PR-AUC": average_precision_score(y_true, y_prob),
        "Brier Score": brier_score_loss(y_true, y_prob),
        "TP": tp,
        "TN": tn,
        "FP": fp,
        "FN": fn
    }


results = []
pred_store = {}

for model_name, model in trained_models.items():
    test_loss, test_acc, test_f1, y_true, y_pred, y_prob = run_one_epoch(model, test_loader)

    metrics = compute_metrics(y_true, y_pred, y_prob)
    metrics["Model"] = model_name
    metrics["Test Loss"] = test_loss

    results.append(metrics)
    pred_store[model_name] = {
        "y_true": y_true,
        "y_pred": y_pred,
        "y_prob": y_prob
    }

results_df = pd.DataFrame(results)

cols = [
    "Model", "Test Loss", "Accuracy", "Precision", "Recall/Sensitivity",
    "Specificity", "F1-score", "Balanced Accuracy", "MCC",
    "Cohen Kappa", "ROC-AUC", "PR-AUC", "Brier Score",
    "TP", "TN", "FP", "FN"
]

results_df = results_df[cols]
print(results_df.round(4).to_string(index=False))
results_df.to_csv("/content/salmon_model_test_metrics.csv", index=False)

# Cell 13: Confusion matrices

for model_name, item in pred_store.items():
    cm = confusion_matrix(item["y_true"], item["y_pred"])

    plt.figure(figsize=(5,4))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=class_names,
        yticklabels=class_names
    )
    plt.title(f"{model_name}: Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.tight_layout()
    plt.show()

# Cell 14: ROC and PR curves

from sklearn.metrics import roc_curve, precision_recall_curve, auc

for model_name, item in pred_store.items():
    y_true = item["y_true"]
    y_prob = item["y_prob"]

    fpr, tpr, _ = roc_curve(y_true, y_prob)
    precision, recall, _ = precision_recall_curve(y_true, y_prob)

    plt.figure(figsize=(6,5))
    plt.plot(fpr, tpr, label=f"AUC = {auc(fpr, tpr):.4f}")
    plt.plot([0,1], [0,1], linestyle="--")
    plt.title(f"{model_name}: ROC Curve")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(6,5))
    plt.plot(recall, precision, label=f"AP = {average_precision_score(y_true, y_prob):.4f}")
    plt.title(f"{model_name}: Precision-Recall Curve")
    plt.xlabel("Recall")
    plt.ylabel("Precision")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Cell 15: Copy-paste classification reports

for model_name, item in pred_store.items():
    print("\n" + "="*100)
    print(model_name)
    print("="*100)
    print(classification_report(
        item["y_true"],
        item["y_pred"],
        target_names=class_names,
        digits=4
    ))

# Cell 16: Hybrid ensemble

top_models = results_df.sort_values("F1-score", ascending=False)["Model"].head(3).tolist()
print("Top models used for hybrid ensemble:", top_models)

y_true = pred_store[top_models[0]]["y_true"]
avg_prob = np.mean([pred_store[m]["y_prob"] for m in top_models], axis=0)
avg_pred = (avg_prob >= 0.5).astype(int)

ensemble_metrics = compute_metrics(y_true, avg_pred, avg_prob)
ensemble_metrics["Model"] = "Hybrid_Probability_Ensemble_Top3"
ensemble_metrics["Test Loss"] = np.nan

ensemble_df = pd.DataFrame([ensemble_metrics])[cols]
print(ensemble_df.round(4).to_string(index=False))

# Cell 17: McNemar statistical test


best_two = results_df.sort_values("F1-score", ascending=False)["Model"].head(2).tolist()

m1, m2 = best_two

y_true = pred_store[m1]["y_true"]
p1 = pred_store[m1]["y_pred"]
p2 = pred_store[m2]["y_pred"]

correct1 = p1 == y_true
correct2 = p2 == y_true

table = [
    [np.sum(correct1 & correct2), np.sum(correct1 & ~correct2)],
    [np.sum(~correct1 & correct2), np.sum(~correct1 & ~correct2)]
]

result = mcnemar(table, exact=True)

print("Compared models:", m1, "vs", m2)
print("McNemar contingency table:", table)
print("Statistic:", result.statistic)
print("p-value:", result.pvalue)

# Cell 18: Inference speed benchmark

def benchmark_model(model, loader):
    model.eval()
    n = 0

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    start = time.time()

    with torch.no_grad():
        for x, _ in loader:
            x = x.to(DEVICE)
            _ = forward_logits(model, x)
            n += x.size(0)

    if DEVICE == "cuda":
        torch.cuda.synchronize()

    elapsed = time.time() - start

    return {
        "Images": n,
        "Total Time (s)": elapsed,
        "Images/sec": n / elapsed,
        "ms/image": (elapsed / n) * 1000
    }


benchmarks = []

for model_name, model in trained_models.items():
    b = benchmark_model(model, test_loader)
    b["Model"] = model_name
    benchmarks.append(b)

bench_df = pd.DataFrame(benchmarks)
print(bench_df.round(4).to_string(index=False))
bench_df.to_csv("/content/salmon_inference_benchmark.csv", index=False)

# Cell 19: YOLO26 classifier

from ultralytics import YOLO

yolo_model = YOLO("yolo26n-cls.pt")

yolo_results = yolo_model.train(
    data=str(WORK_DIR),
    epochs=30,
    imgsz=224,
    batch=32,
    device=0 if torch.cuda.is_available() else "cpu",
    project="/content/yolo26_salmon",
    name="yolo26n_cls_salmon",
    seed=SEED
)

# Cell 20: YOLO26 validation

best_yolo_path = "/content/yolo26_salmon/yolo26n_cls_salmon/weights/best.pt"

best_yolo = YOLO(best_yolo_path)

yolo_metrics = best_yolo.val(
    data=str(WORK_DIR),
    split="test",
    imgsz=224,
    device=0 if torch.cuda.is_available() else "cpu"
)

print("YOLO26 Top-1 Accuracy:", yolo_metrics.top1)
print("YOLO26 Top-5 Accuracy:", yolo_metrics.top5)

# Cell 21: Export all publication tables

final_results_df = pd.concat([results_df, ensemble_df], ignore_index=True)

with pd.ExcelWriter("/content/salmon_publication_results_full.xlsx") as writer:
    dist_df.to_excel(writer, sheet_name="Dataset_Distribution", index=False)
    final_results_df.to_excel(writer, sheet_name="Model_Test_Metrics", index=False)
    bench_df.to_excel(writer, sheet_name="Inference_Benchmark", index=False)

print("Saved: /content/salmon_publication_results_full.xlsx")
print(final_results_df.round(4).to_string(index=False))